frameworkVersion: "^2.1.0"

service: ${self:custom.productPhotos.assignName}

custom:
  stage: ${opt:stage, self:provider.stage, self:custom.private.stage}
  private: ${file(../../private.yml)}
  helloRetail: ${file(../../helloRetail.yml)}
  productPhotos: ${file(../productPhotos.yml)}

provider:
  name: aws
  runtime: nodejs12.x
  region: ${self:custom.private.region}
  memorySize: ${env:MEMORY_SIZE}
  timeout: 65
  iam:
    role:
      statements: # permissions for all of your functions can be set here
        - Effect: Allow
          Action: # Gives permission to DynamoDB tables in a specific region
            - dynamodb:PutItem
          Resource: !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${MetricsTablePhotoAssign}"

functions:
  assign:
    role:
      'Fn::GetAtt': [ AssignRole, Arn ]
    handler: assign.handler
    environment:
      ACTIVITY_RECEIVE_ARN: ${self:custom.productPhotos.receiveActivityArn}
      TABLE_PHOTO_ASSIGNMENTS_NAME:
        Fn::ImportValue: ${self:custom.productPhotos.exportPhotoAssignmentsTableName}
      TABLE_PHOTO_REGISTRATIONS_NAME:
        Fn::ImportValue: ${self:custom.productPhotos.exportPhotoRegistrationsTableName}

resources:
  Resources:
    MetricsTablePhotoAssign:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: metrics.photo-assign
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    # Log Group
    AssignLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: '/aws/lambda/${self:service}-${self:custom.stage}-assign'
        RetentionInDays: 7
    # Role
    AssignRole: # role for the assignment creation lambda
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: ${self:custom.stage}ProductPhotosAssign${self:custom.productPhotos.productPhotosVersion}
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: sts:AssumeRole
              Principal:
                Service: lambda.amazonaws.com
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AWSLambda_FullAccess
          - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        Policies:
          - PolicyName: CreateAndWriteToLogStream
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'logs:CreateLogStream'
                  Resource:
                    'Fn::GetAtt': [ AssignLogGroup, Arn ]
                - Effect: Allow
                  Action:
                    - 'logs:PutLogEvents'
                  Resource:
                    'Fn::Join':
                      - ':'
                      - - 'Fn::GetAtt': [ AssignLogGroup, Arn ]
                        - '*'
          - PolicyName: GetAndFailActivityTask
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'states:GetActivityTask'
                    - 'states:SendTaskFailure'
                  Resource: ${self:custom.productPhotos.receiveActivityArn}
          - ${self:custom.productPhotos.updatePhotoAssignment}
          - ${self:custom.productPhotos.queryPhotoRegistrationsAssignmentsIndex}
          - ${self:custom.productPhotos.updatePhotoRegistrations}
  Outputs:
    AssignLambdaName:
      Description: The Name of the Photo Assignments Assign Lambda
      Value:
        Ref: AssignLambdaFunction
      Export:
        Name: ${self:custom.productPhotos.exportPhotoAssignmentsAssignLambdaName}
    AssignLambdaArn:
      Description: The Name of the Photo Assignments Assign Lambda
      Value:
        'Fn::GetAtt': [ AssignLambdaFunction, Arn ]
      Export:
        Name: ${self:custom.productPhotos.exportPhotoAssignmentsAssignLambdaArn}
