frameworkVersion: "^2.1.0"

service: ${self:custom.productPhotos.successName}

custom:
  stage: ${opt:stage, self:provider.stage, self:custom.private.stage}
  private: ${file(../../private.yml)}
  helloRetail: ${file(../../helloRetail.yml)}
  productPhotos: ${file(../productPhotos.yml)}

provider:
  name: aws
  runtime: nodejs12.x
  region: ${self:custom.private.region}
  memorySize: ${env:MEMORY_SIZE}
  iam:
    role:
      statements: # permissions for all of your functions can be set here
        - Effect: Allow
          Action: # Gives permission to DynamoDB tables in a specific region
            - dynamodb:PutItem
          Resource: !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${MetricsTablePhotoSuccess}"

functions:
  success:
    role:
      'Fn::GetAtt': [ SuccessRole, Arn ]
    handler: success.handler

resources:
  Resources:
    MetricsTablePhotoSuccess:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: metrics.photo-success
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    # Log Group
    SuccessLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: '/aws/lambda/${self:service}-${self:custom.stage}-success'
        RetentionInDays: 7
    # Role
    SuccessRole: # role for the assignment succeeding lambda
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: ${self:custom.stage}ProductPhotosSuccess${self:custom.productPhotos.productPhotosVersion}
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: sts:AssumeRole
              Principal:
                Service: lambda.amazonaws.com
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AWSLambda_FullAccess
          - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        Policies:
          - PolicyName: CreateAndWriteToLogStream
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'logs:CreateLogStream'
                  Resource:
                    'Fn::GetAtt': [ SuccessLogGroup, Arn ]
                - Effect: Allow
                  Action:
                    - 'logs:PutLogEvents'
                  Resource:
                    'Fn::Join':
                      - ':'
                      - - 'Fn::GetAtt': [ SuccessLogGroup, Arn ]
                        - '*'
  Outputs:
    SuccessLambdaName:
      Description: The Name of the Photo Assignments Success Lambda
      Value:
        Ref: SuccessLambdaFunction
      Export:
        Name: ${self:custom.productPhotos.exportPhotoAssignmentsSuccessLambdaName}
    SuccessLambdaArn:
      Description: The Name of the Photo Assignments Success Lambda
      Value:
        'Fn::GetAtt': [ SuccessLambdaFunction, Arn ]
      Export:
        Name: ${self:custom.productPhotos.exportPhotoAssignmentsSuccessLambdaArn}
