frameworkVersion: "^2.1.0"

service: ${self:custom.productPhotos.failName}

custom:
  stage: ${opt:stage, self:provider.stage, self:custom.private.stage}
  private: ${file(../../private.yml)}
  helloRetail: ${file(../../helloRetail.yml)}
  productPhotos: ${file(../productPhotos.yml)}

provider:
  name: aws
  runtime: nodejs12.x
  region: ${self:custom.private.region}
  memorySize: ${env:MEMORY_SIZE}
  iam:
    role:
      statements: # permissions for all of your functions can be set here
        - Effect: Allow
          Action: # Gives permission to DynamoDB tables in a specific region
            - dynamodb:PutItem
          Resource: !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${MetricsTablePhotoFail}"

functions:
  fail:
    role:
      'Fn::GetAtt': [ FailRole, Arn ]
    handler: fail.handler
    environment:
      TABLE_PHOTO_ASSIGNMENTS_NAME:
        Fn::ImportValue: ${self:custom.productPhotos.exportPhotoAssignmentsTableName}

resources:
  Resources:
    MetricsTablePhotoFail:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: metrics.photo-fail
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    # Log Group
    FailLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: '/aws/lambda/${self:service}-${self:custom.stage}-fail'
        RetentionInDays: 7
    # Role
    FailRole: # role for the assignment failing lambda
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: ${self:custom.stage}ProductPhotosFail${self:custom.productPhotos.productPhotosVersion}
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: sts:AssumeRole
              Principal:
                Service: lambda.amazonaws.com
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AWSLambda_FullAccess
          - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        Policies:
          - PolicyName: CreateAndWriteToLogStream
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'logs:CreateLogStream'
                  Resource:
                    'Fn::GetAtt': [ FailLogGroup, Arn ]
                - Effect: Allow
                  Action:
                    - 'logs:PutLogEvents'
                  Resource:
                    'Fn::Join':
                      - ':'
                      - - 'Fn::GetAtt': [ FailLogGroup, Arn ]
                        - '*'
          - ${self:custom.productPhotos.deletePhotoAssignment}
  Outputs:
    FailLambdaName:
      Description: The Name of the Photo Assignments Fail Lambda
      Value:
        Ref: FailLambdaFunction
      Export:
        Name: ${self:custom.productPhotos.exportPhotoAssignmentsFailLambdaName}
    FailLambdaArn:
      Description: The Name of the Photo Assignments Fail Lambda
      Value:
        'Fn::GetAtt': [ FailLambdaFunction, Arn ]
      Export:
        Name: ${self:custom.productPhotos.exportPhotoAssignmentsFailLambdaArn}
